# Generated by Django 6.0.1 on 2026-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
